# Generated by Django 5.2.6 on 2025-09-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('location', models.CharField()),
                ('image', models.ImageField(upload_to='')),
                ('context', models.TextField()),
                ('naver_link', models.URLField()),
            ],
        ),
    ]
